export const suzukiEngine = {
  name: 'suzukiEngine',
  title: 'Produkt — Suzuki Motor',
  type: 'document',
  groups: [
    { name: 'info',  title: 'Informasjon', default: true },
    { name: 'media', title: 'Bilete' },
  ],
  fields: [
    {
      name: 'modelName',
      title: 'Modellnamn',
      type: 'string',
      group: 'info',
      description: 'Eks: DF9.9B / DF90A / DF150AP',
      validation: (R) => R.required(),
    },
    {
      name: 'slug',
      title: 'Slug (URL)',
      type: 'slug',
      group: 'info',
      options: { source: 'modelName', maxLength: 64 },
      validation: (R) => R.required(),
    },
    {
      name: 'hp',
      title: 'Hestekrefter',
      type: 'string',
      group: 'info',
      description: 'Eks: 9,9 hk / 90 hk',
    },
    {
      name: 'type',
      title: 'Motortype / teknologi',
      type: 'string',
      group: 'info',
      description: 'Eks: EFI · Lean Burn / DOHC · 4-takt',
    },
    {
      name: 'priceFrom',
      title: 'Pris frå',
      type: 'string',
      group: 'info',
      description: 'Berre tal utan "kr". Eks: 18 900',
    },
    {
      name: 'inStock',
      title: 'På lager',
      type: 'boolean',
      group: 'info',
      description: 'Er motoren tilgjengeleg på Kaupanger no?',
      initialValue: true,
    },
    {
      name: 'description',
      title: 'Kort beskriving',
      type: 'text',
      group: 'info',
      rows: 4,
      description: 'Éi til to setningar om motoren. Visast på produktkortet.',
    },
    {
      name: 'order',
      title: 'Rekkefølgje (lågast = øvst)',
      type: 'number',
      group: 'info',
      initialValue: 10,
    },
    {
      name: 'image',
      title: 'Produktbilete',
      type: 'image',
      group: 'media',
      description: 'Bilete av motoren. Helst på kvit/transparent bakgrunn.',
      options: { hotspot: true },
    },
  ],
  preview: {
    select: { title: 'modelName', subtitle: 'hp', media: 'image' },
    prepare: ({ title, subtitle, media }) => ({
      title,
      subtitle: subtitle ? `${subtitle}` : '',
      media,
    }),
  },
};
